# Generated by Django 5.1.5 on 2025-06-04 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_notification_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="friends_rel", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
