# Generated by Django 5.1.5 on 2025-06-04 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("users", "0004_customuser_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_notifications",
                to="core.message",
            ),
        ),
    ]
