# Generated by Django 5.1.5 on 2025-03-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_description_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="post_picture",
            field=models.ImageField(default="default.jpg", upload_to="posts/"),
        ),
    ]
