# Generated by Django 5.1.5 on 2025-03-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_bookreview_review_picture_reviewcomment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookreview",
            name="book_author",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
