# Generated by Django 5.1.5 on 2025-06-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0006_alter_bookclub_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookclub",
            old_name="location",
            new_name="meeting_location",
        ),
    ]
