# Generated by Django 5.1.5 on 2025-06-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0008_archivedbook_archivedmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookclub",
            name="current_book_picture",
            field=models.ImageField(default="default.jpg", upload_to="clubs/"),
        ),
    ]
