# Generated by Django 5.1.5 on 2025-06-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0009_bookclub_current_book_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedbook",
            name="current_book_picture",
            field=models.ImageField(blank=True, null=True, upload_to="archived_clubs/"),
        ),
    ]
