# Generated by Django 5.1.5 on 2025-06-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0010_archivedbook_current_book_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookclub",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
