# Generated by Django 5.1.5 on 2025-06-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0012_rsvp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookclub",
            name="current_book_picture",
            field=models.ImageField(default="default.jpg", upload_to="book_cover/"),
        ),
    ]
